name: Publish Docker
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: |
          yarn install --frozen-lockfile;
          yarn fa:build --dest=docs;
          yarn docs:build;
          echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin;
          docker build . -t bromberglab/bio-node-docs;
          docker push bromberglab/bio-node-docs;
